"use strict";
// 1) Загальну вартість (нові ціни - price)
// 2) Знайти кількість товарів, у яких ціна зменшилась (price < old_price)
// 2) Товари, які доступні (sell_status:"available")
// 4) сформувати новий список об”єктів тільки доступних  для продажу товарів, 
// які міститимуть тільки ідентифікатор товару (id), нову ціну (price), стару ціну (old_price), 
// та ціну у доларах (usd_price)
if (confirm('Почати тестування?')) {
    const dataList = [
        {
            id: 344277463,
            old_price: 1395,
            old_usd_price: '37.70',
            price: 1099,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '29.70',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 363766641,
            old_price: 0,
            old_usd_price: '0.00',
            price: 90,
            min_month_price: 0,
            sell_status: 'unavailable',
            status: 'active',
            usd_price: '2.43',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 339273715,
            old_price: 38,
            old_usd_price: '1.03',
            price: 25,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '0.68',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 330746665,
            old_price: 3087,
            old_usd_price: '83.43',
            price: 2548,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '68.86',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 344972806,
            old_price: 699,
            old_usd_price: '18.89',
            price: 549,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '14.84',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 318302299,
            old_price: 0,
            old_usd_price: '0.00',
            price: 8500,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '229.73',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 361430565,
            old_price: 3500,
            old_usd_price: '94.59',
            price: 1999,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '54.03',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 14429030,
            old_price: 3339,
            old_usd_price: '90.24',
            price: 2999,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '81.05',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 56340912,
            old_price: 2094,
            old_usd_price: '56.59',
            price: 1776,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '48.00',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 315292225,
            old_price: 1799,
            old_usd_price: '48.62',
            price: 1499,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '40.51',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 28437961,
            old_price: 42999,
            old_usd_price: '1162.14',
            price: 33999,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '918.89',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 339896833,
            old_price: 6399,
            old_usd_price: '172.95',
            price: 5899,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '159.43',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 364354149,
            old_price: 1600,
            old_usd_price: '43.24',
            price: 1500,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '40.54',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: {
                id: 106,
                discount_price: 1300,
                title: 'ціна по промокоду діє з 22.03 по 28.03',
                price_show_in_site_id: 5151,
                show_in_details: 1,
                show_in_catalog: 1,
                is_description: 1,
                description: 'test',
                promo_code: '',
                url_for_image: 'https://rozetka.com.ua/ua/promo/allgalaxies/',
                images: '',
                images_mobile: '',
                hide_price: 0,
            },
        },
        {
            id: 363184995,
            old_price: 0,
            old_usd_price: '0.00',
            price: 4499,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '121.59',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 98077846,
            old_price: 0,
            old_usd_price: '0.00',
            price: 3113,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '84.14',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 310694668,
            old_price: 0,
            old_usd_price: '0.00',
            price: 3000,
            min_month_price: 0,
            sell_status: 'unavailable',
            status: 'active',
            usd_price: '81.08',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 362812029,
            old_price: 0,
            old_usd_price: '0.00',
            price: 21700,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '586.49',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 361422708,
            old_price: 4100,
            old_usd_price: '110.81',
            price: 2699,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '72.95',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 318302257,
            old_price: 0,
            old_usd_price: '0.00',
            price: 8500,
            min_month_price: 0,
            sell_status: 'unavailable',
            status: 'active',
            usd_price: '229.73',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 310694498,
            old_price: 0,
            old_usd_price: '0.00',
            price: 2963,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '80.08',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 363651273,
            old_price: 5199,
            old_usd_price: '140.51',
            price: 4890,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '132.16',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 330747022,
            old_price: 3087,
            old_usd_price: '83.43',
            price: 2606,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '70.43',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 362617635,
            old_price: 4872,
            old_usd_price: '131.68',
            price: 2436,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '65.84',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
        {
            id: 363614439,
            old_price: 5199,
            old_usd_price: '140.51',
            price: 4890,
            min_month_price: 0,
            sell_status: 'available',
            status: 'active',
            usd_price: '132.16',
            pl_charge_pcs: 0,
            pl_use_instant_bonus: false,
            pl_premium_bonus_charge_pcs: 0,
            rests: -1,
            min_price: 0,
            max_price: 0,
            has_shops: false,
            info: null,
            show_in_site: null,
        },
    ];
    // 1)
    /**
     * the function makes the total cost of all products from the price
     * @param arr accepts a list of products
     * @returns the total cost of all products from the price
     */
    function getTotalCoast(arr) {
        const totalCoast = arr.reduce((productSum, product) => product.price > 0 ? productSum + product.price : productSum, 0);
        return totalCoast;
    }
    // 2)
    /**
     * the function compares products with the price at the old price
     * @param arr accepts a list of products
     * @returns the number of items where the price is less than the old price
     */
    function priceChanged(arr) {
        const changes = arr.filter((product) => product.price < product.old_price).length;
        return changes;
    }
    // 3)
    /**
     * the function checks an array of objects for the presence of sell_status:'available'
     * @param arr accepts a list of products
     * @returns an array of objects with sell_status:'available'
     */
    function getAvailableProducts(arr) {
        const availableProducts = arr.filter((product) => product.sell_status === 'available');
        return availableProducts;
    }
    // 4)
    /**
     * the function creates a new array of objects
     * @param arr accepts a list of products
     * @returns a new array of objects
     */
    function getAvailableForSale(arr) {
        const newAvailable = arr.map((product) => ({
            id: product.id,
            price: product.price,
            old_price: product.old_price,
            usd_price: product.usd_price
        }));
        return newAvailable;
    }
    document.write(`
        <h2 class="homework__title">Рішення:</h2>
        <div>Відповіді можливо побачити тільки в консолі!</div>
        <hr>
    `);
    console.log(dataList);
    console.log(`Загальна вартість - ${getTotalCoast(dataList)}`);
    console.log(`Кількість товарів, у яких ціна зменшилась (price < old_price) -  ${priceChanged(dataList)}`);
    console.log('Товари, які доступні (sell_status:"available")');
    console.log(getAvailableProducts(dataList));
    console.log('Новий список об”єктів:');
    console.log(getAvailableForSale(dataList));
}
else {
    alert(`Нажаль ви відмовились від теста 😞`);
}
